### ISSUE TITLE
Paypal window does not appear, and donate page shows error message

### ISSUE THREAD

**Issue by danielfmiranda** [mozilla/donate-wagtail#1635]
## Tasks:

- [x] Find out how to reproduce error (see The Issue below) 
- [x] Figure out what is causing the error - outcome: Error caused by http 429 being returend from paypal
- [x] Update stakeholders (Stephanie Lowry) regarding source of error and possible fixes or improvements
- _Figure out how to catch http 429 status codes_ - the [PayPal Checkout.js library](https://github.com/paypal/paypal-checkout) function that is used [braintree-web/paypal-checkout](https://braintree.github.io/braintree-web/3.24.1/module-braintree-web_paypal-checkout.html#.create) does not  return the http status codes.  So this part of the ask is dropped.
- [ ] Change [generalErrorMsg in paypal.js ](https://github.com/mozilla/donate-wagtail/blob/50a365891aadc51bb85b226a410dafb0c398d4f9/source/js/components/paypal.js#L17) to read
`Unable to connect to Paypal.  Please try again in a few minutes. `

### The issue
the issue presents before the donation is made - so after entering a value into donate other amount field, which is under $10 then clicking the Paypal button - the Paypal popup window never appears and the error message: “There was an error processing your payment. Please try again.” 

<img width="1516" alt="Screen Shot 2022-01-19 at 10 58 23 AM" src="https://user-images.githubusercontent.com/18314510/151618366-20d126f5-6e05-4a53-8cc1-5d8d38844952.png">

<img width="421" alt="Screen Shot 2022-01-18 at 1 44 27 PM" src="https://user-images.githubusercontent.com/18314510/151618390-56a188e0-e575-4ead-85c2-0fca0fbe2989.png">

Expected Result:
<img width="1476" alt="Screen Shot 2022-01-28 at 2 42 14 PM" src="https://user-images.githubusercontent.com/18314510/151618633-7d2e7f10-9092-4907-9a59-e2bbf56d1815.png">

  Resolution for this would be: better error message.  “Could not connect to paypal server.  Please disable pop-blockers or try a different browser.”  

###Steps:
- [x] Try to reproduce this by maybe by enabling a pop-up blocker on a browser.   If having trouble reach out to Stephanie on donor care to see how they reproduce the issue. 

Paypal Error Docs: https://developer.paypal.com/docs/checkout/standard/customize/handle-errors/

**Comment by Pomax** [comment]
I can't reproduce this. No matter what amount I fill in, the paypal donate window shows up, whether in private browsing or already logged into paypal.

**Comment by stephanielowry** [comment]
@danielfmiranda  I tested this in Firefox, Safari and on my iPhone (Safari) and things are working as expected now. 

Previously, the error message would appear for amounts under $10 in the browsers listed above on the main donate.mozilla.org page (no special URL). I haven't changed any settings or didn't access the page a different way either.

**Comment by stephanielowry** [comment]
I did get the error for the Thunderbird page using Firefox just now using this link: https://give.thunderbird.net/en-US/
<img width="918" alt="Screen Shot 2022-01-31 at 8 52 40 PM" src="https://user-images.githubusercontent.com/30730118/151914644-d52141f9-0c31-4c2a-8dce-0d62d7f7b816.png">

**Comment by danielfmiranda** [comment]
Hi everyone! 

This is proving to be a difficult issue to reproduce, as I am experiencing the same thing as Pomax, attempting to reproduce this issue on any browser with/without adblock installed on the browser/incognito modes turned on/etc all seem to work for me. However, I was able to reproduce the error following these specific steps:

After repeatedly trying to donate a small amount for some time (opening and closing the paypal window), I then experience something similar to the bug that Stephanie is reporting. The error message gets displayed, the paypal window gets closed out, and a 429 Rate Limit Code is thrown in the requests response:

<img width="718" alt="Screen Shot 2022-02-07 at 3 42 14 PM" src="https://user-images.githubusercontent.com/18314510/152890742-54327255-3174-4d6f-a848-dd4077b75b62.png">


I then took a look into the code to see where this error is being caught, and found it here:
https://github.com/mozilla/donate-wagtail/blob/c4f543fb2e027cc390e94288a2aac5b9a03baa08/source/js/components/paypal.js#L101-L108


I then confirmed that this is where the error is being produced, by adding in some custom text in the error message function and then reproducing the bug by getting the 429 code:

<img width="718" alt="Screen Shot 2022-02-07 at 3 47 06 PM" src="https://user-images.githubusercontent.com/18314510/152891200-80a8320f-d916-4809-9456-15c2e1b14277.png">

I was then hoping the error logged by the function above might be able to give us some context to work with, to do something like generate a new, more descriptive message if a user has hit their limit for the time period. However when logging the error to the console, this not quite helpful message appears:

<img width="718" alt="Screen Shot 2022-02-07 at 3 49 32 PM" src="https://user-images.githubusercontent.com/18314510/152891377-9fd4e096-1b72-413e-b0b4-fd45ef6859cb.png">

After taking a look here in the paypal developer documentation: https://developer.paypal.com/docs/checkout/standard/customize/handle-errors/

It appears that this error is generic by design and meant to be used with a generic error message. 

To quote the docs "This error handler is a catch-all. Errors at this point are not expected to be handled beyond showing a generic error message or page."

That leads me to believe that this error might be on the braintree/paypal admin side as the error is produced when limiting the user from making small time donations, which I assume is something we implemented to counter fraud.

However after reaching out to Stephanie however to ask if this error was produced while testing the donate site repeatedly, she said she was able to reproduce it on her sons phone who does not visit the donate site regularly. 



**This leads me to some questions for @jzinner @Pomax when they have the time:**

- Do you think this could be caused by braintree/paypal rate limiting? (If so, maybe we can move this ticket to be worked on after we get the fraud amounts and such under control in ticket #1633, since the goal of that ticket is to update our fraud prevention settings.)
- @jzinner While a easy solution to this problem would be catching the rate limit error and then returning a specific message letting the user know, the paypal docs lead me to believe that catching the specific error type is not possible. Is there a reworded "catch-all" error statement that you would like me to add in place of "There was an error processing your payment. Please try again." 


Thank you all for taking the time to read my comment!

**Comment by Pomax** [comment]
It honestly sounds like at this point it's not so much "Rate limiting" as in your case, but by @stephanielowry having ended up on a Paypal block list. (which we'll never learn through any API call) and it might be necessary to contact Paypal to find out what's going on.

**Comment by danielfmiranda** [comment]
Got it, thanks @Pomax! 

@stephanielowry by any chance is it possible for you to reach out to paypal to find if this could be the case? Please let me know if there is anything I can assist with, thanks!

**Comment by stephanielowry** [comment]
I'm not on any block list, because I'm not putting my email address on the form, I'm using different browsers and sometimes it goes through. Donors are experiencing this same issue, but when I give them the URL with donorcare in it, they seem to have no trouble. The issue is the main donate.mozilla.org page and the give.thunderbird.net page. I use PayPal for all kinds of other things, and trying a few times I can get it through on the donate & tbird pages as well.

**Comment by danielfmiranda** [comment]
Got it @stephanielowry! Thank you for the heads up and for helping us troubleshoot as we try and find the cause for this.
After meeting with @jzinner, they brought to my attention that this could be a case of rate limiting, as they forwarded me an email from braintree stating that as of Jan 6 this year, braintree did indicate that they were seeing unusual traffic from our URL and that if the rates did not return to normal that they can would enforce a rate limit.

To quote the email “Any requests that exceed this limit will receive a Too Many Requests (429, which is the same response that I am getting) and can be safely retried later.

@stephanielowry, I remember you mentioning that even trying the donate site on your sons phone would produce this bug, and after the response from braintree above, I believe the cause of this may be that the limit is network-wide instead of device specific. I also say this because I experience the same thing if I am getting the 429 response and then try again on a mobile device or on a different browser.

In terms of next steps, I think it would be helpful to update the language on the error message that gets produced, but since we are unable to distinguish the difference between a 429 error and other errors that may occur (see comment above), we would still have to keep it pretty general.

I propose something along the lines of “Error connecting to PayPal. Please donate with card or try again later”. as I think this gives a little more context then the message “There was an error processing your payment. Please try again.” especially considering this bug occurs before a payment is even made.

Tagging @Pomax to hear his thoughts as well

**Comment by jzinner** [comment]
Hi @danielfmiranda, Thank you for your efforts on this one.

So what's left to close this issue is: 

- [ ] Change [generalErrorMsg in paypal.js ](https://github.com/mozilla/donate-wagtail/blob/50a365891aadc51bb85b226a410dafb0c398d4f9/source/js/components/paypal.js#L17)to read

`Unable to connect to Paypal. Please try again in a few minutes.`
