### ISSUE TITLE
Design a 403 page

### ISSUE THREAD

**Issue by kristinashu** [mozilla/donate-wagtail#1651]
Request via @jzinner and @anilkanji: improve our 403 Forbidden oage on donate.mozilla.org based on the [issue raised in slack](https://mozilla.slack.com/archives/C4M19QU2Z/p1648500286230469).

Screen cap of 403 error:
<img width="311" alt="image" src="https://user-images.githubusercontent.com/1068783/163855847-c80b2b21-5c84-4b08-95a7-8ad31afe099c.png">

Currently, donors who use a VPN see a 403 error page. This is expected behaviour since it is intended to help prevent fraud however current design is the default and needs to be more inline with Mozilla's branding to improve the user experience.

## Todo
- [ ] Decide on copy (I'd recommend something about suggesting users to disable their VPN and if they continue to see the error then to contact donor care)
- [ ] Mockup the page in a similar style as the 404 page https://donate.mozilla.org/en-US/404/ 
- [ ] Share with stakeholders (Stephanie Lowry and Anil) for feeback
- [ ] Open ticket for dev implementation, cc @jzinner in the dev ticket since Jen will need to add the redirect from the default page to our stylized page

Screen cap of branded 404 error:
<img width="1263" alt="image" src="https://user-images.githubusercontent.com/1068783/163856014-1e09880a-1f16-4910-8ee0-a077728e0f7b.png">

Note related tickets https://github.com/mozilla/donate-wagtail/issues/1645 https://github.com/mozilla/donate-wagtail/issues/1650

**Comment by cdanfon** [comment]
We will do the dev work for this ticket under [#1650](https://github.com/mozilla/donate-wagtail/issues/1650)

**Comment by kristinashu** [comment]
@sabrinang will link to the svg file for the 404 illustration so it can be updated to 403

**Comment by mofodevops** [comment]
I'm sure designers are on top of of this already, but just for clarity.  Donate will still need the 404 page.  

Ideally, make a copy of the 404 page and use it as a template to generate a separate 403 page.

**Comment by sabrinang** [comment]
SVG file here: https://drive.google.com/open?id=0B3b1KWRwjxtoWE1tcjNPMmpmTEE&resourcekey=0-EOSUAf9SsBkvwTl6JYa6VA&authuser=sabrina%40mozillafoundation.org&usp=drive_fs

Feel free to assign design work to me as I've iterated on this 404 graphic before

**Comment by anilkanji** [comment]
Is this the right place to suggest copy?  Something like:

**One Moment - Action Required - VPN**

Supporters like you make possible our fight for a healthy internet - thank you. We take your privacy very seriously; **However to minimize fraudulent payments**  we're asking supporters to disable VPN when donating to the Foundation.

Please disable your VPN and then navigate to donate.mozilla.org again - thank you.

[and then some other option - i.e. through paypal if they really don't want to disable VPN]

**Comment by anilkanji** [comment]
note to incorporate feedback from this thread: https://mozilla.slack.com/archives/C4M19QU2Z/p1650914868532369?thread_ts=1648500286.230469&cid=C4M19QU2Z

**Comment by sabrinang** [comment]
@anilkanji Here's a redpen to a mockup and some 403 emoji variants: https://redpen.io/p/mb226ac6a7d095211a

- I think the title can be shorter or have less dashes
- If you have copy for paypal option I can include that too
- Steph L also mentioned about directing users back to their email campaign URL so that can be in the copy as well
![403-mockup@2x](https://user-images.githubusercontent.com/2492510/165196479-959d473a-eeaa-4ba7-b1b5-b1fa9b3627b6.jpg)

**Comment by kristinashu** [comment]
Thank you @sabrinang! Maybe try sharing this in the slack thread with Anil and Stephanie?

**Comment by anilkanji** [comment]
Thanks Sabrina - copy requests in redpen -ping me on slack if they're confusing. Stephanie and I also put together a quick supporter journey map which made me realize this is happening _after_ a donor has input all of their payment details. Just FYI
![403 supporter story map](https://user-images.githubusercontent.com/46638654/165604340-322c9a35-6bd5-49d1-8048-93854a21e845.png)
.

**Comment by sabrinang** [comment]
@anilkanji Thanks for the copy and I updated the redpen https://redpen.io/p/mb226ac6a7d095211a with your comments. Let me know if there is anything else and if that emoji expression works for the 403 graphic.

**Comment by jzinner** [comment]
Hi @anilkanji - sorry to step in - as I am very happy with Sabrina's help and progress on this. Thank you 

But wanted to say that the 403 page will occur BEFORE users have input their information.  

The WAF evaluates what IP a users is connecting from, and based on that IP address will either send them a 403 or allow them to pass on to the donate site.

**Comment by sabrinang** [comment]
@anilkanji I got copy from the slack thread and updated the redpen: https://redpen.io/jhf067d89912be0736

**Comment by anilkanji** [comment]
Thanks @sabrinang -one small edit in redpen requested, but then I think we should be good to go.

**Comment by sabrinang** [comment]
Updated the [redpen](https://redpen.io/jhf067d89912be0736) @anilkanji!

**Comment by anilkanji** [comment]
Thanks again - looks good to go to me!

**Comment by sabrinang** [comment]
**Mockup:**
see [redpen](https://redpen.io/jhf067d89912be0736)

**Illustration:** 
[exported svg file](https://drive.google.com/open?id=1azYJ1aBwYhq7kkbn0cdH4bNFnn2164DI&authuser=sabrina%40mozillafoundation.org&usp=drive_fs)

**Copy for Devs:**
```
Action Required - VPN Issue

Please disable your VPN and visit donate.mozilla.org again.

We take your privacy very seriously. To minimize fraudulent payments, we’re asking supporters to disable their VPNs when visiting our donate page.
```
