### ISSUE TITLE
QA: User Interface

### ISSUE THREAD

**Issue by alanmoo** [mozilla/donate-wagtail#252]
Master QA ticket for User Flow, mainly around UI. 

If an item is not completely passing, file a new ticket and edit this post to link to it. For example:
- [ ] A thing that should work, but doesn't (#1234)

Any QA tickets that don't show a reference from a master issue will be closed.
### Changes that need to be made across the site:
- [ ] Footer UI changes #273
- [ ] Add 'per month' label to buttons when monthly is selected #275 
- [ ] Change border radius of credit card button to match paypal button #281
- [ ] Hamburger menu needs to be centered to mozilla logo  #282
- [ ] Fix 'other amount' field on iOS #286
- [ ] Lack of error state styling #305 

### Specific Pages
- [x] Main donate page
  - [x] Desktop #372, #373, #374, #375  
  - [x] iOS
  - [x] Android
- [x] A campaign page
  - [x] Desktop
    - [ ] Make 'other amount button' full width #280
    - [ ]  Refine Campaign Header Spacing (P2) #314 
  - [x] iOS
  - [x] Android
- [x] Credit card form
  - [x] Desktop
    - [ ] Fix Change Amount Button #276
    - [ ] Fix button and form field heights #288
    - [ ] Missing period #289 
  - [x] iOS
     - [ ] Fix form fields on iOS #290
  - [x] Android
      - [ ] Fix form fields on Android #303
- [x] Upsell view
  - [] Desktop #338 
  - [x] iOS
    - [ ] Fix alignment of consent text and consent checkbox on iOS #307
  - [x] Android
    - [ ] Consent checkbox missing on Android #308
- [x] Newsletter signup
  - [x] Desktop
  - [x] iOS
  - [x] Android
- [x] Thank you page/Social share #371 
  - [x] Desktop
  - [x] iOS
  - [x] Android
     - [ ] Fix hover state of social buttons #311
