### ISSUE TITLE
QA: Localization

### ISSUE THREAD

**Issue by alanmoo** [mozilla/donate-wagtail#255]
Master QA ticket for localization.

If an item is not completely passing, file a new ticket and edit this post to link to it. For example:
- [x] Some locales are not supported (#332)
- [x] Country list is not localized (#358)
- [x] “Country” field is not localizable (#362)
- [x] Unlocalized strings in post-payment sign-up form (#369)
- [x] “Other amount” placeholder not localized after switching currency (#387)
- [ ] Consider making postcode optional (#415)
- [x] Site name is not localizable (#489)

Any QA tickets that don't show a reference from a master issue will be closed.

- [x] Capturing non-English characters in donation flow (#261)
- [x] Support non-English browsers (#260)
- [x] `es-*` pages are loading translations from the `es.po` file
- [x] URLs
  - [x] URL switching behavior works as expected
- [x] Changing currency
- [ ] Strings
  - [x]  Main donate page
  - [ ]  A campaign page
  - [x]  Credit card form
  - [x]  Upsell view
  - [ ]  Newsletter signup
  - [x]  Thank you page/Social share
- [ ] Receipts
