### ISSUE TITLE
QA: Performance

### ISSUE THREAD

**Issue by alanmoo** [mozilla/donate-wagtail#256]
Master QA ticket for site performance.

If an item is not completely passing, file a new ticket and edit this post to link to it. For example:
- [ ] A thing that should work, but doesn't (#1234)

Any QA tickets that don't show a reference from a master issue will be closed.

- [ ] Front end assets are minified
- [x] Load testing to maximum experienced in last year of the existing site #270
- [ ] Ensure there are no red lab data items on a [Google Page Speed test](https://developers.google.com/speed/pagespeed/insights/)/

Issues Filed:

- [x] [Paypal JS minification](https://github.com/mozilla/donate-wagtail/issues/291)
- [x] [Gzip compression](https://github.com/mozilla/donate-wagtail/issues/292)
- [ ] [Below the fold CSS](https://github.com/mozilla/donate-wagtail/issues/293)
- [x] [CSS minification](https://github.com/mozilla/donate-wagtail/issues/294)
