### ISSUE TITLE
QA: Security

### ISSUE THREAD

**Issue by alanmoo** [mozilla/donate-wagtail#258]
Master QA ticket for Security

If an item is not completely passing, file a new ticket and edit this post to link to it. For example:
- [x] A thing that should work, but doesn't (#1234)

Any QA tickets that don't show a reference from a master issue will be closed.

- [x] SSL Observatory score of at least B+

@cadecairos @patjouk Please edit this list, as I'm sure it's not complete.

Filed Issues:

- [x] [csrftoken cookie is insecure](https://github.com/mozilla/donate-wagtail/issues/295)
- [x] [CSP](https://github.com/mozilla/donate-wagtail/issues/296)
- [x] [5xx from bogus amount in querystring](https://github.com/mozilla/donate-wagtail/issues/297)

**Comment by cadecairos** [comment]
Our SSL observatory score is at a B, which is as high as we can get it with a security policy that is costing us -20 points on out score (Thanks card payment industry!)
