### ISSUE TITLE
Checklist for launching CMS content localization

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla/donate-wagtail#447]
- [ ] Create a separate repository for CMS content
- [ ] Add https://github.com/mozilla-pontoon as collaborator and make sure master is not protected
- [ ] Check that FAQ and Ways to give page content is final in CMS
- [ ] Check the list of locales
- [ ] Add a project-config file to donate-wagtail, referencing the CMS repo
- [ ] Setup the CMS repo as a secondary repo in the Donate project in Pontoon
- [ ] Enable French, test full flow and localized pages
- [ ] Enable all locales

**Comment by TheoChevalier** [comment]
We can finally close this one 🎉 Localization should start soon
