### ISSUE TITLE
Infra checklist (donate-wagtail-production)

### ISSUE THREAD

**Issue by cadecairos** [mozilla/donate-wagtail#479]
- [x] Create App
- [x] Add Braintree to app config
- [x] Add scaling (hirefire)
- [x] Enable ReCAPTCHA
- [x] Create AWS credentials for S3 & SQS, add to config
- [x] Domain - Set up Heroku ACM so we have a CNAME to set it to.
- [x] Lock root page to admin login
- [x] Set web concurrency
- [X] Set up Sentry 
- [x] double check Environment
- [x] Webhooks - Done-ish, the webhook is using the herokuapp domain, and will need to be switched over to the final domain when we have it. **add recurring transaction webhook**
- [x] Pontoon commit credentials
- [ ] Staff accounts (Editor: Will, Theo, Steph) (Admin: Alan, Lucie, Chris, Gideon)
~~- [ ] Prepare launch pages~~

I will add more things as I think of them

**Comment by alanmoo** [comment]
Staff accounts will be taken care of as the SSO lands.

**Comment by patjouk** [comment]
We forgot to add alerting on Heroku. I'm opening a ticket.
